
package vista;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author bourdier
 */
public class DatosPersonales extends javax.swing.JPanel {

  /**
   * Creates new form DatosPersonales
   */
  public DatosPersonales() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bg = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jId = new javax.swing.JLabel();
    txtId = new javax.swing.JTextField();
    btnAgregar = new javax.swing.JButton();
    jMatricula = new javax.swing.JLabel();
    TxtFechaNacimiento = new javax.swing.JTextField();
    btnActualizar = new javax.swing.JButton();
    jNombres = new javax.swing.JLabel();
    TxtSexo = new javax.swing.JTextField();
    btnBorrar = new javax.swing.JButton();
    jApellidos = new javax.swing.JLabel();
    TxtContactoEmergencia = new javax.swing.JTextField();
    jCorreo = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    TxtBuscar = new javax.swing.JTextField();
    jbuscar = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    btnRefrescar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    TblPersonales = new javax.swing.JTable();
    TxtCarreraActual = new javax.swing.JTextField();

    bg.setBackground(new java.awt.Color(255, 255, 255));
    bg.setPreferredSize(new java.awt.Dimension(1070, 610));

    jLabel2.setBackground(new java.awt.Color(0, 0, 0));
    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel2.setText("Formulario del estudiante");

    jId.setBackground(new java.awt.Color(0, 0, 0));
    jId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jId.setText("Id");

    txtId.setEditable(false);
    txtId.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    txtId.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdActionPerformed(evt);
      }
    });

    btnAgregar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnAgregar.setText("Agregar");
    btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAgregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAgregarActionPerformed(evt);
      }
    });

    jMatricula.setBackground(new java.awt.Color(0, 0, 0));
    jMatricula.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jMatricula.setText("Fecha");

    TxtFechaNacimiento.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    btnActualizar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnActualizar.setText("Actualizar");
    btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jNombres.setBackground(new java.awt.Color(0, 0, 0));
    jNombres.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jNombres.setText("Sexo");

    TxtSexo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    btnBorrar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnBorrar.setText("Borrar");
    btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnBorrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBorrarActionPerformed(evt);
      }
    });

    jApellidos.setBackground(new java.awt.Color(0, 0, 0));
    jApellidos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jApellidos.setText("Contacto");

    TxtContactoEmergencia.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    jCorreo.setBackground(new java.awt.Color(0, 0, 0));
    jCorreo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    jCorreo.setText("Carrera");

    jLabel3.setBackground(new java.awt.Color(0, 0, 0));
    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel3.setText("Tabla de contenido");

    TxtBuscar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TxtBuscarActionPerformed(evt);
      }
    });

    jbuscar.setBackground(new java.awt.Color(0, 0, 0));
    jbuscar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jbuscar.setText("Buscar");

    jLabel1.setBackground(new java.awt.Color(0, 0, 0));
    jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabel1.setText("*Selecionar un estudiante para actualizar, borrar o ampliar");

    btnRefrescar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnRefrescar.setText("Refrescar");
    btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRefrescarActionPerformed(evt);
      }
    });

    TblPersonales.setBackground(new java.awt.Color(102, 0, 102));
    TblPersonales.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
    TblPersonales.setForeground(new java.awt.Color(255, 255, 255));
    TblPersonales.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {

      }
    ));
    TblPersonales.setGridColor(new java.awt.Color(255, 255, 255));
    TblPersonales.setSelectionBackground(new java.awt.Color(51, 0, 51));
    TblPersonales.setSelectionForeground(new java.awt.Color(255, 255, 255));
    jScrollPane1.setViewportView(TblPersonales);

    TxtCarreraActual.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
    bg.setLayout(bgLayout);
    bgLayout.setHorizontalGroup(
      bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgLayout.createSequentialGroup()
        .addGap(46, 46, 46)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(bgLayout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jCorreo)
              .addComponent(jId)
              .addComponent(jNombres))
            .addGap(18, 18, 18)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(TxtCarreraActual, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(bgLayout.createSequentialGroup()
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)
                    .addComponent(jMatricula))
                  .addGroup(bgLayout.createSequentialGroup()
                    .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jApellidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(TxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(TxtContactoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(bgLayout.createSequentialGroup()
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(jLabel1)
          .addGroup(bgLayout.createSequentialGroup()
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(btnActualizar)
              .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnRefrescar)))
        .addContainerGap(225, Short.MAX_VALUE))
    );
    bgLayout.setVerticalGroup(
      bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgLayout.createSequentialGroup()
        .addGap(31, 31, 31)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jMatricula)
          .addComponent(jId))
        .addGap(36, 36, 36)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(TxtContactoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jApellidos)
          .addComponent(jNombres))
        .addGap(36, 36, 36)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TxtCarreraActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jCorreo))
        .addGap(26, 26, 26)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAgregar)
          .addComponent(btnActualizar)
          .addComponent(btnBorrar))
        .addGap(42, 42, 42)
        .addComponent(jLabel3)
        .addGap(9, 9, 9)
        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jbuscar)
          .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnRefrescar))
        .addGap(5, 5, 5)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(18, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdActionPerformed

  private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAgregarActionPerformed

  private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnBorrarActionPerformed

  private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TxtBuscarActionPerformed

  private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

  }//GEN-LAST:event_btnRefrescarActionPerformed

  public ComponentUI getUi() {
    return ui;
  }

  public void setUi(ComponentUI ui) {
    this.ui = ui;
  }

  public EventListenerList getListenerList() {
    return listenerList;
  }

  public void setListenerList(EventListenerList listenerList) {
    this.listenerList = listenerList;
  }

  public AccessibleContext getAccessibleContext() {
    return accessibleContext;
  }

  public void setAccessibleContext(AccessibleContext accessibleContext) {
    this.accessibleContext = accessibleContext;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable TblPersonales;
  private javax.swing.JTextField TxtBuscar;
  private javax.swing.JTextField TxtCarreraActual;
  private javax.swing.JTextField TxtContactoEmergencia;
  private javax.swing.JTextField TxtFechaNacimiento;
  private javax.swing.JTextField TxtSexo;
  private javax.swing.JPanel bg;
  private javax.swing.JButton btnActualizar;
  private javax.swing.JButton btnAgregar;
  private javax.swing.JButton btnBorrar;
  private javax.swing.JButton btnRefrescar;
  private javax.swing.JLabel jApellidos;
  private javax.swing.JLabel jCorreo;
  private javax.swing.JLabel jId;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jMatricula;
  private javax.swing.JLabel jNombres;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel jbuscar;
  private javax.swing.JTextField txtId;
  // End of variables declaration//GEN-END:variables

  public JTable getTblPersonales() {
    return TblPersonales;
  }

  public void setTblPersonales(JTable TblPersonales) {
    this.TblPersonales = TblPersonales;
  }

  public JTextField getTxtBuscar() {
    return TxtBuscar;
  }

  public void setTxtBuscar(JTextField TxtBuscar) {
    this.TxtBuscar = TxtBuscar;
  }

  public JTextField getTxtCarreraActual() {
    return TxtCarreraActual;
  }

  public void setTxtCarreraActual(JTextField TxtCarreraActual) {
    this.TxtCarreraActual = TxtCarreraActual;
  }

  public JTextField getTxtContactoEmergencia() {
    return TxtContactoEmergencia;
  }

  public void setTxtContactoEmergencia(JTextField TxtContactoEmergencia) {
    this.TxtContactoEmergencia = TxtContactoEmergencia;
  }

  public JTextField getTxtFechaNacimiento() {
    return TxtFechaNacimiento;
  }

  public void setTxtFechaNacimiento(JTextField TxtFechaNacimiento) {
    this.TxtFechaNacimiento = TxtFechaNacimiento;
  }

  public JTextField getTxtSexo() {
    return TxtSexo;
  }

  public void setTxtSexo(JTextField TxtSexo) {
    this.TxtSexo = TxtSexo;
  }

  public JPanel getBg() {
    return bg;
  }

  public void setBg(JPanel bg) {
    this.bg = bg;
  }

  public JButton getBtnActualizar() {
    return btnActualizar;
  }

  public void setBtnActualizar(JButton btnActualizar) {
    this.btnActualizar = btnActualizar;
  }

  public JButton getBtnAgregar() {
    return btnAgregar;
  }

  public void setBtnAgregar(JButton btnAgregar) {
    this.btnAgregar = btnAgregar;
  }

  public JButton getBtnBorrar() {
    return btnBorrar;
  }

  public void setBtnBorrar(JButton btnBorrar) {
    this.btnBorrar = btnBorrar;
  }

  public JButton getBtnRefrescar() {
    return btnRefrescar;
  }

  public void setBtnRefrescar(JButton btnRefrescar) {
    this.btnRefrescar = btnRefrescar;
  }

  public JTextField getTxtId() {
    return txtId;
  }

  public void setTxtId(JTextField txtId) {
    this.txtId = txtId;
  }

  public DatosPersonales(JTable TblPersonales, JTextField TxtBuscar, JTextField TxtCarreraActual, JTextField TxtContactoEmergencia, JTextField TxtFechaNacimiento, JTextField TxtSexo, JPanel bg, JButton btnActualizar, JButton btnAgregar, JButton btnBorrar, JButton btnRefrescar, JLabel jbuscar, JTextField txtId) {
    this.TblPersonales = TblPersonales;
    this.TxtBuscar = TxtBuscar;
    this.TxtCarreraActual = TxtCarreraActual;
    this.TxtContactoEmergencia = TxtContactoEmergencia;
    this.TxtFechaNacimiento = TxtFechaNacimiento;
    this.TxtSexo = TxtSexo;
    this.bg = bg;
    this.btnActualizar = btnActualizar;
    this.btnAgregar = btnAgregar;
    this.btnBorrar = btnBorrar;
    this.btnRefrescar = btnRefrescar;
    this.jbuscar = jbuscar;
    this.txtId = txtId;
  }

  

}
