package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author bourdier
 */
public class Login extends javax.swing.JFrame {
  

  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
    setLocationRelativeTo(null);
  }
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    Derechalogin = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    Izquierdalogin = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtcorreologin = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtpasswordlogin = new javax.swing.JPasswordField();
    btnLogin = new javax.swing.JButton();
    btnSignUp = new javax.swing.JButton();
    jLabel7 = new javax.swing.JLabel();
    BtnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("LOGIN");
    setBackground(new java.awt.Color(255, 255, 255));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));
    jPanel3.setLayout(null);

    Derechalogin.setBackground(new java.awt.Color(51, 51, 51));
    Derechalogin.setPreferredSize(new java.awt.Dimension(400, 500));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));

    jLabel3.setBackground(new java.awt.Color(204, 204, 204));
    jLabel3.setForeground(new java.awt.Color(102, 102, 102));
    jLabel3.setText("copyright @ company name All rigths reserved");

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/fondologin.jpg"))); // NOI18N
    jLabel8.setText("jLabel8");

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/gif.gif"))); // NOI18N
    jLabel9.setText("jLabel9");

    javax.swing.GroupLayout DerechaloginLayout = new javax.swing.GroupLayout(Derechalogin);
    Derechalogin.setLayout(DerechaloginLayout);
    DerechaloginLayout.setHorizontalGroup(
      DerechaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(DerechaloginLayout.createSequentialGroup()
        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(466, 466, 466)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(DerechaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabel2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    DerechaloginLayout.setVerticalGroup(
      DerechaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DerechaloginLayout.createSequentialGroup()
        .addGroup(DerechaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(DerechaloginLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGap(935, 935, 935))
          .addGroup(DerechaloginLayout.createSequentialGroup()
            .addGroup(DerechaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel8)
              .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addComponent(jLabel3)
        .addGap(52, 52, 52))
    );

    jPanel3.add(Derechalogin);
    Derechalogin.setBounds(0, 0, 400, 500);

    Izquierdalogin.setBackground(new java.awt.Color(51, 0, 51));
    Izquierdalogin.setForeground(new java.awt.Color(255, 255, 255));
    Izquierdalogin.setPreferredSize(new java.awt.Dimension(400, 500));

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Inicia sesión ");

    jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Correo");

    txtcorreologin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    txtcorreologin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

    jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Constraseña");

    txtpasswordlogin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    txtpasswordlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txtpasswordlogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtpasswordloginActionPerformed(evt);
      }
    });

    btnLogin.setBackground(new java.awt.Color(51, 51, 51));
    btnLogin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(255, 255, 255));
    btnLogin.setText("Login");
    btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btnSignUp.setBackground(new java.awt.Color(51, 51, 51));
    btnSignUp.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
    btnSignUp.setText("Sign Up");
    btnSignUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnSignUp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSignUpActionPerformed(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("No tengo una cuenta");

    BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
    BtnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
    BtnCancelar.setText("Cancelar");
    BtnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout IzquierdaloginLayout = new javax.swing.GroupLayout(Izquierdalogin);
    Izquierdalogin.setLayout(IzquierdaloginLayout);
    IzquierdaloginLayout.setHorizontalGroup(
      IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaloginLayout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addGroup(IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaloginLayout.createSequentialGroup()
            .addComponent(jLabel4)
            .addGap(122, 122, 122))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaloginLayout.createSequentialGroup()
            .addGroup(IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addGroup(IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(txtpasswordlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addComponent(txtcorreologin))
              .addComponent(jLabel6)
              .addGroup(IzquierdaloginLayout.createSequentialGroup()
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(IzquierdaloginLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(24, 24, 24))))
    );
    IzquierdaloginLayout.setVerticalGroup(
      IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(IzquierdaloginLayout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addComponent(jLabel4)
        .addGap(27, 27, 27)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtcorreologin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtpasswordlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, Short.MAX_VALUE)
        .addGroup(IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
        .addGroup(IzquierdaloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(btnSignUp))
        .addGap(54, 54, 54))
    );

    jPanel3.add(Izquierdalogin);
    Izquierdalogin.setBounds(400, 0, 400, 500);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

    this.dispose();
  }//GEN-LAST:event_btnSignUpActionPerformed

  private void txtpasswordloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordloginActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtpasswordloginActionPerformed

  /**
   * @param args the command line arguments
   */
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton BtnCancelar;
  private javax.swing.JPanel Derechalogin;
  private javax.swing.JPanel Izquierdalogin;
  public javax.swing.JButton btnLogin;
  public javax.swing.JButton btnSignUp;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel3;
  public javax.swing.JTextField txtcorreologin;
  public javax.swing.JPasswordField txtpasswordlogin;
  // End of variables declaration//GEN-END:variables

   public JButton getBtnLogin() {
        return btnLogin;
    }

    public JButton getBtnCancelar() {
        return BtnCancelar;
    }

    public JTextField getTxtCorreoLogin() {
        return txtcorreologin;
    }

    public JPasswordField getTxtpasswordlogin() {
        return txtpasswordlogin;
    }
}

