
package vista;

import javax.accessibility.AccessibleContext;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author bourdier
 */
public class Perfil extends javax.swing.JPanel {

  /**
   * Creates new form DatosPersonales
   */
  public Perfil() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bg = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    bg.setBackground(new java.awt.Color(255, 255, 255));
    bg.setPreferredSize(new java.awt.Dimension(1070, 610));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Costruccion.gif"))); // NOI18N
    jLabel1.setText("jLabel1");

    javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
    bg.setLayout(bgLayout);
    bgLayout.setHorizontalGroup(
      bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgLayout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(0, 310, Short.MAX_VALUE))
    );
    bgLayout.setVerticalGroup(
      bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bgLayout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(0, 82, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  public ComponentUI getUi() {
    return ui;
  }

  public void setUi(ComponentUI ui) {
    this.ui = ui;
  }

  public EventListenerList getListenerList() {
    return listenerList;
  }

  public void setListenerList(EventListenerList listenerList) {
    this.listenerList = listenerList;
  }

  public AccessibleContext getAccessibleContext() {
    return accessibleContext;
  }

  public void setAccessibleContext(AccessibleContext accessibleContext) {
    this.accessibleContext = accessibleContext;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bg;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables

  
}
