package vista;

import controlador.ControladorLogin;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author bourdier
 */
public class SignUp extends javax.swing.JFrame {

  /**
   * Creates new form SignUp
   */
  public SignUp() {
    initComponents();
    setLocationRelativeTo(null);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JtableSignUp = new javax.swing.JPanel();
    PanelDerechoRegistro = new javax.swing.JPanel();
    jLabelRegistrate = new javax.swing.JLabel();
    jLabelNombre = new javax.swing.JLabel();
    txtnombreregistro = new javax.swing.JTextField();
    jLabelTengounacuenta = new javax.swing.JLabel();
    txtpasswordregistro = new javax.swing.JPasswordField();
    btnLogin = new javax.swing.JButton();
    btnSignUp = new javax.swing.JButton();
    txtcorreoregistro = new javax.swing.JTextField();
    jLabelCorreo = new javax.swing.JLabel();
    jLabelContrasena = new javax.swing.JLabel();
    PanelIzquierdoRegistro = new javax.swing.JPanel();
    jLabelcompany = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    JtableSignUp.setBackground(new java.awt.Color(255, 255, 255));
    JtableSignUp.setToolTipText("Sign Up");
    JtableSignUp.setPreferredSize(new java.awt.Dimension(800, 500));
    JtableSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    PanelDerechoRegistro.setBackground(new java.awt.Color(51, 0, 51));
    PanelDerechoRegistro.setPreferredSize(new java.awt.Dimension(400, 500));

    jLabelRegistrate.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabelRegistrate.setForeground(new java.awt.Color(255, 255, 255));
    jLabelRegistrate.setText("Registrate");

    jLabelNombre.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
    jLabelNombre.setText("Nombre completo");

    txtnombreregistro.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    jLabelTengounacuenta.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabelTengounacuenta.setForeground(new java.awt.Color(255, 255, 255));
    jLabelTengounacuenta.setText("Tengo una cuenta");

    txtpasswordregistro.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    txtpasswordregistro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtpasswordregistroActionPerformed(evt);
      }
    });

    btnLogin.setBackground(new java.awt.Color(51, 51, 51));
    btnLogin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(255, 255, 255));
    btnLogin.setText("Login");
    btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    btnSignUp.setBackground(new java.awt.Color(51, 51, 51));
    btnSignUp.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
    btnSignUp.setText("Sign Up");
    btnSignUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnSignUp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSignUpActionPerformed(evt);
      }
    });

    txtcorreoregistro.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

    jLabelCorreo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
    jLabelCorreo.setText("Correo");

    jLabelContrasena.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
    jLabelContrasena.setForeground(new java.awt.Color(255, 255, 255));
    jLabelContrasena.setText("Constraseña");

    javax.swing.GroupLayout PanelDerechoRegistroLayout = new javax.swing.GroupLayout(PanelDerechoRegistro);
    PanelDerechoRegistro.setLayout(PanelDerechoRegistroLayout);
    PanelDerechoRegistroLayout.setHorizontalGroup(
      PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelDerechoRegistroLayout.createSequentialGroup()
        .addContainerGap(53, Short.MAX_VALUE)
        .addGroup(PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoRegistroLayout.createSequentialGroup()
            .addGroup(PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(PanelDerechoRegistroLayout.createSequentialGroup()
                .addComponent(jLabelTengounacuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabelNombre)
              .addComponent(jLabelCorreo)
              .addComponent(jLabelContrasena))
            .addGap(154, 154, 154))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoRegistroLayout.createSequentialGroup()
            .addComponent(jLabelRegistrate)
            .addGap(142, 142, 142))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoRegistroLayout.createSequentialGroup()
            .addGroup(PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(txtpasswordregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(txtcorreoregistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addComponent(txtnombreregistro, javax.swing.GroupLayout.Alignment.LEADING)))
            .addGap(32, 32, 32))))
    );
    PanelDerechoRegistroLayout.setVerticalGroup(
      PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelDerechoRegistroLayout.createSequentialGroup()
        .addGap(77, 77, 77)
        .addComponent(jLabelRegistrate)
        .addGap(31, 31, 31)
        .addComponent(jLabelNombre)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtnombreregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(10, 10, 10)
        .addComponent(jLabelCorreo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtcorreoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabelContrasena)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtpasswordregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
        .addGroup(PanelDerechoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLogin)
          .addComponent(jLabelTengounacuenta))
        .addGap(26, 26, 26))
    );

    JtableSignUp.add(PanelDerechoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 430, -1));

    PanelIzquierdoRegistro.setBackground(new java.awt.Color(51, 51, 51));
    PanelIzquierdoRegistro.setMinimumSize(new java.awt.Dimension(400, 500));
    PanelIzquierdoRegistro.setPreferredSize(new java.awt.Dimension(400, 500));
    PanelIzquierdoRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabelcompany.setBackground(new java.awt.Color(204, 204, 204));
    jLabelcompany.setForeground(new java.awt.Color(102, 102, 102));
    jLabelcompany.setText("copyright @ company name All rigths reserved");
    PanelIzquierdoRegistro.add(jLabelcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 506, -1, -1));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/gifsignup.gif"))); // NOI18N
    jLabel2.setText("jLabel2");
    PanelIzquierdoRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

    JtableSignUp.add(PanelIzquierdoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

    getContentPane().add(JtableSignUp, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtpasswordregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordregistroActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtpasswordregistroActionPerformed

  private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

//    SignUp SignUpFrame = new SignUp();
//    SignUpFrame.setVisible(true);
//    SignUpFrame.pack();
//    SignUpFrame.setLocationRelativeTo(null);
//    this.dispose();
  }//GEN-LAST:event_btnSignUpActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    Login LoginFrame = new Login();
    new ControladorLogin(new Login());
    //LoginFrame.setVisible(true);
    LoginFrame.pack();
    LoginFrame.setLocationRelativeTo(null);
    this.dispose();
  }//GEN-LAST:event_btnLoginActionPerformed

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//   // SignUpDAO signdao = new SignUpDAO();
//    Usuarios user = new Usuarios();
//    SignUp signv = new SignUp();
//    ControladorSignUp controlador = new ControladorSignUp(signv,user);
//    signv.setVisible(true);
//    
//
//
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        //new SignUp().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel JtableSignUp;
  private javax.swing.JPanel PanelDerechoRegistro;
  private javax.swing.JPanel PanelIzquierdoRegistro;
  private javax.swing.JButton btnLogin;
  public javax.swing.JButton btnSignUp;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabelContrasena;
  private javax.swing.JLabel jLabelCorreo;
  private javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelRegistrate;
  private javax.swing.JLabel jLabelTengounacuenta;
  private javax.swing.JLabel jLabelcompany;
  public javax.swing.JTextField txtcorreoregistro;
  public javax.swing.JTextField txtnombreregistro;
  public javax.swing.JPasswordField txtpasswordregistro;
  // End of variables declaration//GEN-END:variables

  public JTextField getTxtcorreoregistro() {
    return txtcorreoregistro;
  }

  public JTextField getTxtnombreregistro() {
    return txtnombreregistro;
  }

  public JPasswordField getTxtpasswordregistro() {
    return txtpasswordregistro;
  }

//  public Object getbtnSignUp() {
//    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//  }

}
